language: node_js
node_js:
  - "iojs"
  - "0.12"
  - "0.10"
  - "0.8"
script:
  - bower install
  - npm install
  - npm test
before_install:
  - npm install -g npm bower-cli grunt-cli karma
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
